# Generated by Django 4.2.4 on 2023-09-19 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(default=' ', max_length=100)),
                ('Last_name', models.CharField(default=' ', max_length=100)),
                ('Age', models.IntegerField(default='', max_length=100)),
                ('Email', models.CharField(default=' ', max_length=100)),
                ('Salary', models.IntegerField(default='', max_length=100)),
                ('Bonus', models.IntegerField(default='', max_length=100)),
                ('Branch', models.CharField(default=' ', max_length=100)),
                ('Hire_Date', models.DateField()),
                ('Phone', models.IntegerField(default='', max_length=100)),
                ('Dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.department')),
                ('Roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.role')),
            ],
        ),
    ]
